import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import * as fs from 'fs/promises';
import * as path from 'path';
import { executeJsx } from '../../executor/jsx-runner.js';
import { formatToolResult } from '../tool-executor.js';
import { DESTRUCTIVE_ANNOTATIONS, coerceBoolean } from '../modify/shared.js';
import { colorToRGB } from './check-contrast.js';
/**
 * extract_design_tokens — デザイントークン（色・タイポグラフィ・スペーシング）の抽出
 * @see https://ai-scripting.docsforadobe.dev/jsobjref/Swatches/ — Swatches
 * @see https://ai-scripting.docsforadobe.dev/jsobjref/CharacterAttributes/ — size, textFont
 */
const jsxCode = `
var preflight = preflightChecks();
if (preflight) {
  writeResultFile(RESULT_PATH, preflight);
} else {
  try {
    var doc = app.activeDocument;
    var isCMYKDoc = (doc.documentColorSpace === DocumentColorSpace.CMYK);

    // Layers to skip (generated by place_style_guide / place_color_chips)
    var skipLayers = { "Style Guide": true, "Color Chips": true };

    var fillColors = [];
    var strokeColors = [];
    for (var i = 0; i < doc.pathItems.length; i++) {
      var item = doc.pathItems[i];
      try {
        if (skipLayers[item.layer.name]) continue;
        if (item.filled) fillColors.push(colorToObject(item.fillColor));
        if (item.stroked) strokeColors.push(colorToObject(item.strokeColor));
      } catch(e) {}
    }

    var fontEntries = [];
    var textBounds = [];
    for (var ti = 0; ti < doc.textFrames.length; ti++) {
      var tf = doc.textFrames[ti];
      try {
        if (skipLayers[tf.layer.name]) continue;
        var b = tf.geometricBounds;
        textBounds.push({ left: b[0], top: b[1], right: b[2], bottom: b[3] });
        for (var ri = 0; ri < tf.textRanges.length; ri++) {
          var tr = tf.textRanges[ri];
          try {
            var ca = tr.characterAttributes;
            var fontName = "";
            var fontStyle = "";
            try { fontName = ca.textFont.name; } catch(e2) {}
            try { fontStyle = ca.textFont.style; } catch(e2) {}
            fontEntries.push({
              fontFamily: fontName,
              fontStyle: fontStyle,
              fontSize: ca.size
            });
          } catch(e2) {}
        }
      } catch(e) {}
    }

    // Collect object bounds for spacing analysis
    var objectBounds = [];
    for (var oi = 0; oi < doc.pageItems.length; oi++) {
      try {
        var pItem = doc.pageItems[oi];
        if (skipLayers[pItem.layer.name]) continue;
        var ob = pItem.geometricBounds;
        objectBounds.push({ left: ob[0], top: ob[1], right: ob[2], bottom: ob[3] });
      } catch(e) {}
    }

    writeResultFile(RESULT_PATH, {
      documentColorSpace: isCMYKDoc ? "CMYK" : "RGB",
      fillColors: fillColors,
      strokeColors: strokeColors,
      fontEntries: fontEntries,
      objectBounds: objectBounds
    });
  } catch (e) {
    writeResultFile(RESULT_PATH, { error: true, message: e.message, line: e.line });
  }
}
`;

// --- Node.js post-processing ---

interface ColorObj {
  type: string;
  c?: number;
  m?: number;
  y?: number;
  k?: number;
  r?: number;
  g?: number;
  b?: number;
  [key: string]: unknown;
}

function colorKey(c: ColorObj): string {
  if (c.type === 'cmyk') return `cmyk(${c.c},${c.m},${c.y},${c.k})`;
  if (c.type === 'rgb') return `rgb(${c.r},${c.g},${c.b})`;
  if (c.type === 'spot') return `spot(${c.name},${c.tint})`;
  if (c.type === 'gray') return `gray(${c.value})`;
  if (c.type === 'lab') return `lab(${c.l},${c.a},${c.b})`;
  return `${c.type}`;
}

/** sRGB の #RRGGBB。変換できない色（Lab・成分欠け等）は null（CSS に不正な値を出さない） */
function colorToHex(c: ColorObj): string | null {
  const rgb = colorToRGB(c);
  if (!rgb) return null;
  const to2 = (v: number) => Math.min(255, Math.max(0, Math.round(v))).toString(16).padStart(2, '0');
  return `#${to2(rgb.r)}${to2(rgb.g)}${to2(rgb.b)}`.toUpperCase();
}

/**
 * 隣り合う 2 つの矩形の隙間（Illustrator 座標: top > bottom）。
 * 列挙順に依存しないよう左右・上下どちらの並びでも同じ値を返す。重なっている軸は null
 */
function boundsGaps(
  a: { left: number; top: number; right: number; bottom: number },
  b: { left: number; top: number; right: number; bottom: number },
): { horizontal: number | null; vertical: number | null } {
  const h = Math.max(a.left, b.left) - Math.min(a.right, b.right);
  const v = Math.max(a.bottom, b.bottom) - Math.min(a.top, b.top);
  return { horizontal: h > 0 ? h : null, vertical: v > 0 ? v : null };
}

interface FontEntry {
  fontFamily: string;
  fontStyle: string;
  fontSize: number;
}

function appendWarnings(output: string, warnings?: unknown[]): string {
  if (!warnings || warnings.length === 0) return output;
  return `${output}\n\nWarnings:\n${warnings.map((warning) => `- ${String(warning)}`).join('\n')}`;
}

function formatTokens(
  format: string,
  colors: Array<{ hex: string; original: ColorObj; count: number }>,
  fonts: Array<{ family: string; style: string; size: number; count: number }>,
  spacings: number[],
): string {
  if (format === 'json') {
    const colorObj: Record<string, string> = {};
    colors.forEach((c, i) => {
      const name = i === 0 ? 'primary' : i === 1 ? 'secondary' : i === 2 ? 'tertiary' : `color-${i + 1}`;
      colorObj[name] = c.hex;
    });
    const fontObj: Record<string, { family: string; size: string; weight: string }> = {};
    fonts.forEach((f, i) => {
      const name = i === 0 ? 'heading' : i === 1 ? 'body' : `text-${i + 1}`;
      fontObj[name] = { family: f.family, size: `${f.size}pt`, weight: f.style };
    });
    return JSON.stringify({ color: colorObj, typography: fontObj, spacing: spacings.map((s) => `${s}pt`) }, null, 2);
  }

  if (format === 'tailwind') {
    const colorLines = colors.map((c, i) => {
      const name = i === 0 ? 'primary' : i === 1 ? 'secondary' : i === 2 ? 'tertiary' : `color-${i + 1}`;
      return `        '${name}': '${c.hex}',`;
    });
    const spacingLines = spacings.map((s) => `        '${s}': '${s}pt',`);
    return `// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      colors: {
${colorLines.join('\n')}
      },
      spacing: {
${spacingLines.join('\n')}
      },
    },
  },
};`;
  }

  // CSS (default)
  const lines: string[] = [':root {'];
  colors.forEach((c, i) => {
    const name = i === 0 ? 'primary' : i === 1 ? 'secondary' : i === 2 ? 'tertiary' : `color-${i + 1}`;
    lines.push(`  --color-${name}: ${c.hex};`);
  });
  lines.push('');
  fonts.forEach((f, i) => {
    const name = i === 0 ? 'heading' : i === 1 ? 'body' : `text-${i + 1}`;
    lines.push(`  --font-${name}-family: "${f.family}";`);
    lines.push(`  --font-${name}-size: ${f.size}pt;`);
  });
  if (spacings.length > 0) {
    lines.push('');
    spacings.forEach((s) => {
      lines.push(`  --spacing-${s}: ${s}pt;`);
    });
  }
  lines.push('}');
  return lines.join('\n');
}

export function register(server: McpServer): void {
  server.registerTool(
    'extract_design_tokens',
    {
      title: 'Extract Design Tokens',
      description:
        'Extract colors, typography, and spacing from the document as design tokens in CSS custom properties, JSON, or Tailwind format. Optionally writes the result to output_path (never overwrites an existing file unless overwrite: true).',
      inputSchema: {
        format: z
          .enum(['css', 'json', 'tailwind'])
          .optional()
          .default('css')
          .describe('Output format'),
        output_path: z
          .string()
          .optional()
          .describe('Absolute file path to save the output (e.g. "/path/to/tokens.json"). If omitted, returns text only.'),
        overwrite: coerceBoolean
          .optional()
          .default(false)
          .describe('Replace output_path if it already exists. Default false: an existing file is left untouched and an error is returned.'),
      },
      // output_path + overwrite: true で既存ファイルを置き換えうるため destructive
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    async (params) => {
      const result = (await executeJsx(jsxCode, params)) as {
        fillColors: ColorObj[];
        strokeColors: ColorObj[];
        fontEntries: FontEntry[];
        objectBounds: Array<{ left: number; top: number; right: number; bottom: number }>;
        error?: boolean;
        message?: string;
        warnings?: unknown[];
      };

      if (result.error) {
        return formatToolResult(result);
      }

      const colorCounts = new Map<string, { color: ColorObj; count: number }>();
      for (const c of [...result.fillColors, ...result.strokeColors]) {
        if (c.type === 'none' || c.type === 'pattern' || c.type === 'gradient') continue;
        const key = colorKey(c);
        const existing = colorCounts.get(key);
        if (existing) {
          existing.count++;
        } else {
          colorCounts.set(key, { color: c, count: 1 });
        }
      }

      // sRGB に変換できない色（Lab 等）はトークンに出さず、応答で知らせる
      const skippedColors: string[] = [];
      const sortedColors = [...colorCounts.values()]
        .sort((a, b) => b.count - a.count)
        .flatMap((entry) => {
          const hex = colorToHex(entry.color);
          if (!hex) {
            skippedColors.push(colorKey(entry.color));
            return [];
          }
          return [{ hex, original: entry.color, count: entry.count }];
        })
        .slice(0, 12);

      const fontCounts = new Map<string, { entry: FontEntry; count: number }>();
      for (const f of result.fontEntries) {
        const key = `${f.fontFamily}|${f.fontStyle}|${Math.round(f.fontSize)}`;
        const existing = fontCounts.get(key);
        if (existing) {
          existing.count++;
        } else {
          fontCounts.set(key, { entry: f, count: 1 });
        }
      }

      const sortedFonts = [...fontCounts.values()]
        .sort((a, b) => b.count - a.count)
        .slice(0, 8)
        .map((entry) => ({
          family: entry.entry.fontFamily,
          style: entry.entry.fontStyle,
          size: Math.round(entry.entry.fontSize),
          count: entry.count,
        }));

      // Detect common spacing patterns
      const gaps: number[] = [];
      const bounds = result.objectBounds;
      for (let i = 0; i < bounds.length && i < 100; i++) {
        for (let j = i + 1; j < bounds.length && j < 100; j++) {
          const { horizontal, vertical } = boundsGaps(bounds[i], bounds[j]);
          if (horizontal !== null && horizontal < 200) gaps.push(Math.round(horizontal));
          if (vertical !== null && vertical < 200) gaps.push(Math.round(vertical));
        }
      }

      const gapCounts = new Map<number, number>();
      for (const g of gaps) {
        gapCounts.set(g, (gapCounts.get(g) ?? 0) + 1);
      }
      const commonSpacings = [...gapCounts.entries()]
        .filter(([, count]) => count >= 2)
        .sort((a, b) => b[1] - a[1])
        .slice(0, 6)
        .map(([val]) => val)
        .sort((a, b) => a - b);

      const output = formatTokens(params.format ?? 'css', sortedColors, sortedFonts, commonSpacings);
      const notes: string[] = [];
      if (sortedColors.some((c) => c.original.type !== 'rgb')) {
        notes.push('CMYK / gray / spot colors are converted to hex without an ICC profile (approximate).');
      }
      if (skippedColors.length > 0) {
        notes.push(`Skipped colors with no sRGB equivalent: ${skippedColors.join(', ')}`);
      }
      // 本体は単独の content にする（json をそのままパースできるよう注記は別 content）
      const extras: string[] = [];
      if (notes.length > 0) extras.push(`Notes:\n${notes.map((n) => `- ${n}`).join('\n')}`);
      if (result.warnings && result.warnings.length > 0) {
        extras.push(`Warnings:\n${result.warnings.map((warning) => `- ${String(warning)}`).join('\n')}`);
      }
      const respond = (saved?: string) => ({
        content: [output, ...extras, ...(saved ? [`Saved to: ${saved}`] : [])].map((text) => ({ type: 'text' as const, text })),
      });

      if (params.output_path) {
        const fail = (message: string) => ({
          isError: true,
          content: [{ type: 'text' as const, text: appendWarnings(message, result.warnings) }],
        });
        // 相対パスはサーバープロセスのカレントディレクトリ依存になるため受け付けない
        if (!path.isAbsolute(params.output_path)) {
          return fail(`output_path must be an absolute path: ${params.output_path}`);
        }
        try {
          // 既定では既存ファイルを上書きしない（'wx' は存在すれば EEXIST で失敗する）
          await fs.writeFile(params.output_path, output, { encoding: 'utf-8', flag: params.overwrite ? 'w' : 'wx' });
        } catch (err) {
          if ((err as NodeJS.ErrnoException).code === 'EEXIST') {
            return fail(`File already exists: ${params.output_path}. Set overwrite: true to replace it.`);
          }
          const msg = err instanceof Error ? err.message : String(err);
          return fail(`Failed to write file: ${msg}`);
        }
        return respond(params.output_path);
      }

      return respond();
    },
  );
}
